### ISSUE TITLE
Unable to find smtpd_sasl_password_maps option in postfix documentation

### ISSUE THREAD

**Issue by chas0amx** [bodsch/ansible-postfix#17]
Postfix show warning:
```postconf: warning: /etc/postfix/main.cf: unused parameter: smtpd_sasl_password_maps=```

https://github.com/bodsch/ansible-postfix/blob/b6d39b6928873d617028c0f4d088174da760bc6f/templates/etc/postfix/main.cf.d/smtpd.j2#L94

**Comment by bodsch** [comment]
thanks!
I fix this.
